export enum PL_LABEL_STATUS {
  PENDING = "PENDING",
  SUCCESS = "SUCCESS",
  DISBURSEMENT = "DISBURSEMENT",
  REJECT = "REJECT",
  CANCEL = "CANCEL"
}

export enum PL_MESSAGE_TYPE {
  SUCCESS = "SUCCESS",
  INFORMATION = "INFORMATION",
  WARNING = "WARNING"
}
