export enum PAYDAY_LOAN_STATUS {
  NOT_VERIFY_YET = 'NOT_VERIFY_YET',
  FUNDED = 'FUNDED',
  DOCUMENT_AWAITING = 'DOCUMENT_AWAITING',
  INITIALIZED = 'INITIALIZED',
  AWAITING_APPROVAL = 'AWAITING_APPROVAL',
  DOCUMENTATION_COMPLETE = 'DOCUMENTATION_COMPLETE',
  REJECTED = 'REJECTED',
  WITHDRAW = 'WITHDRAW',
  AUCTION = 'AUCTION',
  CONTRACT_AWAITING = 'CONTRACT_AWAITING',
  CONTRACT_ACCEPTED = 'CONTRACT_ACCEPTED',
  AWAITING_DISBURSEMENT = 'AWAITING_DISBURSEMENT',
  DISBURSED = 'DISBURSED',
  IN_REPAYMENT = 'IN_REPAYMENT',
  COMPLETED = 'COMPLETED',
  OVERDUE_L2 = 'OVERDUE_L2',
  CONTRACT_REJECTED = 'CONTRACT_REJECTED',
  UNKNOWN_STATUS = 'UNKNOWN_STATUS',
  CALLBACK_PAYMENT_RESULT = 'CALLBACK_PAYMENT_RESULT',
}

export enum PL_STEP_NAVIGATION {
  ELECTRONIC_IDENTIFIERS = 'ELECTRONIC_IDENTIFIERS',
  CONFIRM_INFORMATION = 'CONFIRM_INFORMATION',
  ADDITIONAL_INFORMATION = 'ADDITIONAL_INFORMATION',
  CHOOSE_AMOUNT_TO_BORROW = 'CHOOSE_AMOUNT_TO_BORROW',
  CONTRACT_SIGNING = 'CONTRACT_SIGNING',
}

export enum PAYDAY_LOAN_STEP {
  ELECTRONIC_IDENTIFIERS = 1,
  CONFIRM_INFORMATION = 2,
  ADDITIONAL_INFORMATION = 3,
  CHOOSE_AMOUNT_TO_BORROW = 4,
  CONTRACT_SIGNING = 5,
}

export enum PAYDAY_LOAN_STEP_TITLE {
  ELECTRONIC_IDENTIFIERS = 'Định danh điện tử',
  CONFIRM_INFORMATION = 'Xác nhận thông tin',
  ADDITIONAL_INFORMATION = 'Bổ sung thông tin',
  CHOOSE_AMOUNT_TO_BORROW = 'Chọn số tiền cần ứng',
  CONTRACT_SIGNING = 'Ký hợp đồng',
}

export enum DOCUMENT_TYPE {
  ID_CARD = 'ID_CARD',
  FRONT_ID_CARD = 'FRONT_ID_CARD',
  BACK_ID_CARD = 'BACK_ID_CARD',
  SELFIE = 'SELFIE',
  BANK_BOOK = 'BANK_BOOK',
  PAY_SLIP = 'PAY_SLIP',
  UN_KNOWN = 'UN_KNOWN',
  CONTRACT = 'CONTRACT',
  LETTER_OF_ACCEPTANCE = 'LETTER_OF_ACCEPTANCE',
  VEHICLE_REGISTRATION = 'VEHICLE_REGISTRATION',
  SALARY_INFORMATION_ONE = 'SALARY_INFORMATION_ONE',
  SALARY_INFORMATION_TWO = 'SALARY_INFORMATION_TWO',
  SALARY_INFORMATION_THREE = 'SALARY_INFORMATION_THREE',
}

export enum ERROR_CODE {
  ACCOUNT_EXISTED = 'ACCOUNT_EXISTED',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  ACCOUNT_NOT_EXIST = 'ACCOUNT_NOT_EXIST',
  MISS_PARAM = 'MISS_PARAM',
  DATA_ERROR = 'DATA_ERROR',
  WRONG_PASSWORD = 'WRONG_PASSWORD',
  OTP_EXPIRE_TIME = 'OTP_EXPIRE_TIME',
  OTP_INVALID = 'OTP_INVALID',
  OTP_CONFIRM_MAXIMUM = 'OTP_CONFIRM_MAXIMUM',
  SESSION_SIGN_ALREADY_EXIST = 'SESSION_SIGN_ALREADY_EXIST',
  LOCK_CREATE_NEW_SESSION = 'LOCK_CREATE_NEW_SESSION',
  DO_NOT_EXIST_VIRTUAL_ACCOUNT = 'DO_NOT_EXIST_VIRTUAL_ACCOUNT',
  NOT_CURRENT_LOAN_REPAYMENT_ERROR = 'NOT_CURRENT_LOAN_REPAYMENT_ERROR',
  MISSING_ANUAL_INCOME = 'MISSING_ANUAL_INCOME',
  COMPANY_NOT_EXIST = 'COMPANY_NOT_EXIST',
  APPROVAL_LETTER_NOT_EXIST = 'APPROVAL_LETTER_NOT_EXIST',
  DO_NOT_ACTIVE_LOAN_ERROR = 'DO_NOT_ACTIVE_LOAN_ERROR',
  LOAN_NOT_EXIST = 'LOAN_NOT_EXIST',
  NOT_FOUND_SESSION = 'NOT_FOUND_SESSION',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  CORE_ERROR = 'CORE_ERROR',
  VERIFICATION_FAILED = 'VERIFICATION_FAILED',
  ONSIGN_ERROR = 'ONSIGN_ERROR',
  INVALID_LOAN_DATE_ERROR = 'INVALID_LOAN_DATE_ERROR',
  SEND_OTP_ERROR = 'SEND_OTP_ERROR',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
}

export enum ERROR_CODE_KEY {
  ACCOUNT_EXISTED = 'payday_loan.error_code.account_existed',
  EMAIL_ALREADY_EXISTS = 'payday_loan.error_code.email_already_exists',
  ACCOUNT_NOT_EXIST = 'payday_loan.error_code.account_not_exist',
  MISS_PARAM = 'payday_loan.error_code.miss_param',
  DATA_ERROR = 'payday_loan.error_code.data_error',
  WRONG_PASSWORD = 'payday_loan.error_code.wrong_password',
  OTP_EXPIRE_TIME = 'payday_loan.error_code.otp_expire_time',
  OTP_INVALID = 'payday_loan.error_code.otp_invalid',
  OTP_CONFIRM_MAXIMUM = 'payday_loan.error_code.otp_confirm_maximum',
  SESSION_SIGN_ALREADY_EXIST = 'payday_loan.error_code.session_sign_already_exist',
  LOCK_CREATE_NEW_SESSION = 'payday_loan.error_code.lock_create_new_session',
  DO_NOT_EXIST_VIRTUAL_ACCOUNT = 'payday_loan.error_code.do_not_exist_virtual_account',
  NOT_CURRENT_LOAN_REPAYMENT_ERROR = 'payday_loan.error_code.not_current_loan_repayment_error',
  MISSING_ANUAL_INCOME = 'payday_loan.error_code.missing_anual_income',
  COMPANY_NOT_EXIST = 'payday_loan.error_code.company_not_exist',
  APPROVAL_LETTER_NOT_EXIST = 'payday_loan.error_code.approval_letter_not_exist',
  DO_NOT_ACTIVE_LOAN_ERROR = 'payday_loan.error_code.do_not_active_loan_error',
  NOT_FOUND_SESSION = 'payday_loan.error_code.not_found_session',
  INTERNAL_SERVER_ERROR = 'payday_loan.error_code.internal_server_error',
  CORE_ERROR = 'payday_loan.error_code.core_error',
  VERIFICATION_FAILED = 'payday_loan.error_code.verification_failed',
  ONSIGN_ERROR = 'payday_loan.error_code.onsign_error',
  INVALID_LOAN_DATE_ERROR = 'payday_loan.error_code.invalid_loan_date_error',
  SEND_OTP_ERROR = 'payday_loan.error_code.send_otp_error',
  UNKNOWN_ERROR = 'common.something_went_wrong',
  VOUCHER_NOT_EXIST = 'payday_loan.voucher.voucher_not_exist',
  EXPIRED_DATE_VOUCHER_ERROR = 'payday_loan.voucher.expired_date_voucher_error',
  OUT_OF_STOCK_VOUCHER_ERROR = 'payday_loan.voucher.out_of_stock_voucher_error',
  INVALID_TIME_VOUCHER_ERROR = 'payday_loan.voucher.invalid_time_voucher_error',
  MAX_TIME_USED_ERROR = 'payday_loan.voucher.max_time_used_error',
  GET_BANK_LIST_ERROR = 'payday_loan.voucher.get_bank_list_error',
  ACCOUNT_LOCKED = 'payday_loan.error_code.account_locked',
}

export enum SIGN_STATUS {
  ACCEPTED = 'ACCEPTED',
  AWAITING_BORROWER_SIGNATURE = 'AWAITING_BORROWER_SIGNATURE',
  AWAITING_EPAY_SIGNATURE = 'AWAITING_EPAY_SIGNATURE',
  DONE = 'DONE',
}

export enum GPAY_RESULT_STATUS {
  ORDER_PENDING = 'ORDER_PENDING',
  ORDER_PROCESSING = 'ORDER_PROCESSING',
  ORDER_SUCCESS = 'ORDER_SUCCESS',
  ORDER_FAILED = 'ORDER_FAILED',
  ORDER_CANCEL = 'ORDER_CANCEL',
  ORDER_VERIFYING = 'ORDER_VERIFYING',
}

export enum REPAYMENT_STATUS {
  OVERDUE = 'OVERDUE',
}

export enum APPLICATION_TYPE {
  INSURANCE = 'Insurance',
  PDL_TNG = 'PDL_TNG',
  PDL_HMG = 'PDL_HMG',
  PDL_VAC_OFFICE = 'PDL_VAC_OFFICE',
  PDL_VAC_FACTORY = 'PDL_VAC_FACTORY',
}

// export enum RATING_STATUS {
//   NOT_SATISFIED = 'NOT_SATISFIED',
//   SEMI_SATISFIED = 'SEMI_SATISFIED',
//   NORMAL = 'NORMAL',
//   SATISFIED = 'SATISFIED',
//   VERY_SATISFIED = 'VERY_SATISFIED',
// }

export enum COMPANY_NAME {
  HMG = 'HMG',
  TNG = 'TNG',
  VAC = 'VAC',
  VACFACTORY=  'VACFACTORY',
  VACOFFICE=  'VACOFFICE',
}

export enum PAYDAY_LOAN_UI_STATUS {
  NOT_COMPLETE_EKYC_YET = 'NOT_COMPLETE_EKYC_YET',
  NOT_COMPLETE_FILL_EKYC_YET = 'NOT_COMPLETE_FILL_EKYC_YET',
  NOT_ACCEPTING_TERM_YET = 'NOT_ACCEPTING_TERM_YET',
  NOT_COMPLETE_CDE_YET = 'NOT_COMPLETE_CDE_YET',
  COMPLETED_CDE = 'COMPLETED_CDE',
}

export enum PAYDAY_LOAN_TERM_TYPE_VAC {
  ONE_MONTH = 'ONE_MONTH',
  THREE_MONTH = 'THREE_MONTH',
}

